# Token if POSTing (use admin_id for this request)
# https://www.optimizely.com/admin/account_token?account_id=69234495
account:
  id: 3833271397
  admin_id: 3833271397
  token: 6034b3faa802cf11db2a0f99c45a631b:1de2c723


experiment:
  id: 4043552646
  start: 2015-12-02T16:40:0Z
  stop: 2015-12-10T23:30:0Z


goal_ids:
  - &engagement 3838401330
  - &cta_click 4034539833
  - &find_branch 4047802280
  - &visited_get_started 4047654578


segment_ids:
  - &browser 3847450223
  - &mobile 3829910312
  - &source 3836602506
  - &campaign 3835160269


variation_ids:
  - &variation_0 4060552629
  - &variation_2 4059612678


visitors:
  *variation_0:
    total: 10000
  *variation_2:
    total: 10000


conversions:
  engagement:
    goal_ids:
      - *engagement
    counts:
      *variation_0:
        unique: 6554
        total: 6645
      *variation_2:
        unique: 7584
        total: 7602
  cta_click:
    goal_ids:
      - *cta_click
    counts:
      *variation_0:
        unique: 2199
        total: 2240
      *variation_2:
        unique: 3099
        total: 3149
  find_branch:
    goal_ids:
      - *find_branch
    counts:
      *variation_0:
        unique: 1099
        total: 1120
      *variation_2:
        unique: 1430
        total: 1490
  visited_get_started:
    goal_ids:
      - *visited_get_started
    counts:
      *variation_0:
        unique: 2199
        total: 2240
      *variation_2:
        unique: 3099
        total: 3149


segments:
  default:
    *browser:
      ff: 0.35
      ie: 0.15
      gc: 0.40
      safari: 0.10
    *source:
      search: 0.3
      referral: 0.1
      direct: 0.2
      campaign: 0.4
    *campaign:
      dreamforce: 0.2
      students: 0.2
      none: 0.6
  manual:
    *mobile:
      true:
        *variation_0:
          total: 1500
          conversions:
            *engagement: 975
            *cta_click: 330
            *find_branch: 165
            *visited_get_started: 330
        *variation_2:
          total: 1500
          conversions:
            *engagement: 721
            *cta_click: 201
            *find_branch: 101
            *visited_get_started: 201
