# Token if POSTing (use admin_id for this request)
# https://www.optimizely.com/admin/account_token?account_id=69234495
account:
  id: 3833271397
  admin_id: 3833271397
  token: 6034b3faa802cf11db2a0f99c45a631b:1de2c723


experiment:
  id: 4077421977
  start: 2015-12-04T18:10:0Z
  stop: 2015-12-10T23:45:0Z


goal_ids:
  - &engagement 3838401330
  - &app_starts 4118462496
  - &visit_a_branch 4120920579
  - &second_page 4115524087
  - &first_page 4114622713


segment_ids:
  - &browser 3847450223
  - &mobile 3829910312
  - &source 3836602506
  - &campaign 3835160269


variation_ids:
  - &variation_0 4078482206
  - &variation_1 4082871608
  - &variation_2 4069834549


visitors:
  *variation_0:
    total: 10000
  *variation_1:
    total: 10000
  *variation_2:
    total: 10000


conversions:
  engagement:
    goal_ids:
      - *engagement
    counts:
      *variation_0:
        unique: 6554
        total: 6645
      *variation_1:
        unique: 6564
        total: 6655
      *variation_2:
        unique: 7584
        total: 7602
  app_starts:
    goal_ids:
      - *app_starts
    counts:
      *variation_0:
        unique: 2199
        total: 2240
      *variation_1:
        unique: 2200
        total: 2240
      *variation_2:
        unique: 3099
        total: 3149
  visit_a_branch:
    goal_ids:
      - *visit_a_branch
    counts:
      *variation_0:
        unique: 1099
        total: 1120
      *variation_1:
        unique: 1099
        total: 1120
      *variation_2:
        unique: 1430
        total: 1490
  first_page:
    goal_ids:
      - *first_page
    counts:
      *variation_0:
        unique: 10000
        total: 10000
      *variation_1:
        unique: 10000
        total: 10000
      *variation_2:
        unique: 10000
        total: 10000
  second_page:
    goal_ids:
      - *second_page
    counts:
      *variation_0:
        unique: 2199
        total: 2240
      *variation_1:
        unique: 2200
        total: 2240
      *variation_2:
        unique: 3099
        total: 3149


segments:
  default:
    *browser:
      ff: 0.35
      ie: 0.15
      gc: 0.40
      safari: 0.10
    *source:
      search: 0.3
      referral: 0.1
      direct: 0.2
      campaign: 0.4
    *campaign:
      dreamforce: 0.2
      students: 0.2
      none: 0.6
  manual:
    *mobile:
      true:
        *variation_0:
          total: 1500
          conversions:
            *engagement: 975
            *app_starts: 330
            *visit_a_branch: 165
            *first_page: 1500
            *second_page: 330
        *variation_1:
          total: 1500
          conversions:
            *engagement: 976
            *app_starts: 331
            *visit_a_branch: 166
            *first_page: 1500
            *second_page: 331
        *variation_2:
          total: 1500
          conversions:
            *engagement: 721
            *app_starts: 201
            *visit_a_branch: 101
            *first_page: 1500
            *second_page: 201
