# Token if POSTing (use admin_id for this request)
# https://www.optimizely.com/admin/account_token?account_id=69234495
account:
  id: 3151540050
  admin_id: 3151540050
  token: 72252e3ed717c30e32ef


experiment:
  id: 3139710634
  start: 2015-07-07T19:03:0Z
  stop: 2015-07-10T00:07:0Z


goal_ids:
  - &purchase_now 3137690571
  - &revenue_id 3152640018


segment_ids:
  - &browser 2007891079
  - &mobile 2011681251
  - &source 2015320400
  - &campaign 1999830666


variation_ids:
  - &variation_0 3113980556
  - &variation_1 3113720887

visitors:
  *variation_0:
    total: 51262
  *variation_1:
    total: 50982


conversions:
  purchase_now:
    goal_ids:
      - *purchase_now
    counts:
      *variation_0:
        unique: 10680
        total: 42078
      *variation_1:
        unique: 13630
        total: 43058
  revenue_id:
    goal_ids:
      - *revenue_id
    counts:
      *variation_0:
        unique: 6736
        total: 7013
        revenue:
          alpha: 9
          beta: 5
      *variation_1:
        unique: 6734
        total: 7543
        revenue:
          alpha: 11
          beta: 5


segments:
  default:
    *browser:
      ff: 0.35
      ie: 0.15
      gc: 0.40
      safari: 0.10
    *source:
      search: 0.3
      referral: 0.1
      direct: 0.2
      campaign: 0.4
    *campaign:
      seasonal_sale: 0.2
      new_merchandise: 0.2
      none: 0.6
    *mobile:
      true: 0.15
      false: 0.85
