# Token if POSTing (use admin_id for this request)
# https://www.optimizely.com/admin/account_token?account_id=69234495
account:
  id: 3151540050
  admin_id: 3151540050
  token: 72252e3ed717c30e32ef


experiment:
  id: 3137800807
  start: 2015-07-07T19:03:0Z
  stop: 2015-07-13T23:35:0Z


goal_ids:
  - &add_to_cart 3119740234
  - &engagement 3154180340


segment_ids:
  - &browser 3120450780
  - &mobile 3113901074
  - &source 3114931099
  - &campaign 3112701762


variation_ids:
  - &variation_0 3151240542
  - &variation_1 3160280004
  - &variation_2 3174390417


visitors:
  *variation_0:
    total: 51262
  *variation_1:
    total: 50982
  *variation_2:
    total: 51020


conversions:
  add_to_cart:
    goal_ids:
      - *add_to_cart
    counts:
      *variation_0:
        unique: 2358
        total: 2358
      *variation_1:
        unique: 2722
        total: 2722
      *variation_2:
        unique: 3494
        total: 3494
  engagement:
    goal_ids:
      - *engagement
    counts:
      *variation_0:
        unique: 28736
        total: 28736
      *variation_1:
        unique: 29234
        total: 29234
      *variation_2:
        unique: 28302
        total: 28302


segments:
  default:
    *browser:
      ff: 0.35
      ie: 0.15
      gc: 0.40
      safari: 0.10
    *source:
      search: 0.3
      referral: 0.1
      direct: 0.2
      campaign: 0.4
    *campaign:
      seasonal_sale: 0.2
      new_merchandise: 0.2
      none: 0.6
    *mobile:
      true: 0.15
      false: 0.85
