# Token if POSTing (use admin_id for this request)
# https://www.optimizely.com/admin/account_token?account_id=69234495
account:
  id: 3151540050
  admin_id: 3151540050
  token: 72252e3ed717c30e32ef


experiment:
  id: 3137351029
  start: 2015-07-07T19:03:0Z
  stop: 2015-07-13T21:25:0Z


goal_ids:
  - &trips_purchased 3151690003
  - &revenue_id 3152640018
  - &search_now 3159160259


segment_ids:
  - &browser 2007891079
  - &mobile 2011681251
  - &source 2015320400
  - &campaign 1999830666


variation_ids:
  - &variation_0 3121462341
  - &variation_1 3132000917
  - &variation_2 3180850124


visitors:
  *variation_0:
    total: 51262
  *variation_1:
    total: 50982
  *variation_2:
    total: 51020


conversions:
  search_now:
    goal_ids:
      - *search_now
    counts:
      *variation_0:
        unique: 16736
        total: 16736
      *variation_1:
        unique: 17234
        total: 17234
      *variation_2:
        unique: 17702
        total: 17702
  trips_purchased:
    goal_ids:
      - *trips_purchased
      - *revenue_id
    counts:
      *variation_0:
        unique: 6680
        total: 6680
        revenue:
          alpha: 7
          beta: 5
      *variation_1:
        unique: 7630
        total: 7630
        revenue:
          alpha: 8
          beta: 5
      *variation_2:
        unique: 8010
        total: 8010
        revenue:
          alpha: 10
          beta: 5


segments:
  default:
    *browser:
      ff: 0.35
      ie: 0.15
      gc: 0.40
      safari: 0.10
    *source:
      search: 0.3
      referral: 0.1
      direct: 0.2
      campaign: 0.4
    *campaign:
      seasonal_sale: 0.2
      new_merchandise: 0.2
      none: 0.6
    *mobile:
      true: 0.15
      false: 0.85
