# Token if POSTing (use admin_id for this request)
# https://www.optimizely.com/admin/account_token?account_id=69234495
account:
  id: 3512100121
  admin_id: 789421119
  token: aadb541b75eb3527209a61faa6cd9c19:1e7b475c


experiment:
  id: 3510750260
  start: 2015-09-21T21:08:0Z
  stop: 2015-09-28T22:00:0Z

# Bookmark

goal_ids:
  - &engagement 3513620325
  - &new_goal 3543690350
  - &revenue_id 3545310229


segment_ids:
  - &browser 3517710763
  - &mobile 3524820687
  - &source 3527040649


variation_ids:
  - &variation_0 3537430236
  - &variation_1 3541990032
  - &variation_2 3552373891
  - &variation_3 3553403871


visitors:
  *variation_0:
    total: 10000
  *variation_1:
    total: 10000
  *variation_2:
    total: 10000
  *variation_3:
    total: 10000


conversions:
  engagement:
    goal_ids:
      - *engagement
    counts:
      *variation_0:
        unique: 5000
        total: 6000
      *variation_1:
        unique: 7500
        total: 9000
      *variation_2:
        unique: 2500
        total: 3000
      *variation_3:
        unique: 5000
        total: 6000
  new_goal:
    goal_ids:
      - *new_goal
      - *revenue_id
    counts:
      *variation_0:
        unique: 4000
        total: 4500
        revenue:
          alpha: 5
          beta: 11
      *variation_1:
        unique: 6000
        total: 7000
        revenue:
          alpha: 5
          beta: 11
      *variation_2:
        unique: 2000
        total: 2250
        revenue:
          alpha: 5
          beta: 11
      *variation_3:
        unique: 4000
        total: 4500
        revenue:
          alpha: 5
          beta: 11


segments:
  default:
    *browser:
      ff: 0.35
      ie: 0.15
      gc: 0.40
      safari: 0.10
    *source:
      search: 0.3
      referral: 0.1
      direct: 0.2
      campaign: 0.4
    *mobile:
      true: 0.15
      false: 0.85
